<a href="https://colab.research.google.com/github/Ubaldo-Yareli/M-todos-numericos/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El proceso de factorización $LU$, comienza con una matriz $\mbox{n x n}$, es decir, una mtriz cuadrada, a la cual, se le realiza el proceso de $\mbox{eliminación Gaussiana con sustitución hacia atrás}$, con la diferencia de que no se pueden realizar cambios de signos o de filas. La matriz resultante debe ser una matriz diagonal superior y es la que denominaremosn como $U$.

Una vez que se tiene la matriz diagonal superior (con ceros debabajo de cada pivote), la matriz $L$ será una matriz donde la diagonal será de unos con ceros arriba de ellos (es decir, una matriz diagonal inferior) y debajo de los unos se pondrán los coeficientes en el orden en el que se utilizaron al realizar las operaciones elementales (es por eso la importancia de no realizar cambios de signos ni de filas), si ya no se tienen coeficientes y aún hay lugares sin números, se rellenan con ceros.

Para comprobar si $L$ y $U$ son correctas, se puede realizar la multiplicación $LU$ y debe dar como resultado la matriz original $A$.



In [10]:
import numpy as np

def factorizacion_LU(A):
    n=A.shape[0]

    #La matriz proporcionada debe ser una matriz nxn, es decir, una matriz cuadrada
    if A.shape[0]!=A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada.")

    L=np.eye(n) #L se inicializa como la matriz identidad
    U=A.astype(float).copy()

    #Proceso de eliminaión Gaussiana
    for i in range(n):
        if U[i, i]==0:
            raise ValueError("Factorización imposible")

        for j in range(i+1, n):
            factor=U[j, i]/U[i, i]
            L[j, i]=factor
            U[j, i:]=U[j, i:]-factor*U[i, i:]

    return L, U

A=np.array([[1, 1, 0, 3],
            [2, 1, -1, 1],
            [3, -1, -1, 2],
            [-1, 2, 3, -1]], dtype=float)

try:
    L, U=factorizacion_LU(A)
    print("La matriz L es:")
    print(L)
    print("\nLa matriz U es:")
    print(U)
except ValueError as e:
    print(f"Error: {e}")

La matriz L es:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

La matriz U es:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
