<a href="https://colab.research.google.com/github/Ubaldo-Yareli/M-todos-numericos/blob/main/Tutorial_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Numpy es una librería especializada en el cálculo numérico y el análisis de datos, incorporando una calse de datos llamados Arrays, donde se pueden
recolectar una gran cantidad de datos de un mismo tipo en diferentes dimensiones, realizando un procesamiento de forma rápida.

Los arrays seorganizan en forma de tabla o cuadrícula que puede ser de distintas dimensiones, $1D$, $2D$ Y $3D$.

In [2]:
#Un ejemplo de un array de 2 dimesiones
import numpy as np
m=np.array([[1, 2, 3], [4, 5, 6]])
print (m.shape) #Que imprima el tamaño del arreglo
print (m)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [3]:
#Un ejemplo de un array de 3 dimensiones es:
import numpy as np
m=np.array ([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[11, 12, 13], [14, 15, 16], [17, 18, 19]]])
print (m.shape) #Que imprima el tamaño del arreglo
print (m)

(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


El número de dimensiones del array dependerá de las listas o tuplas anidadas en lista.

Un array de una dimensión también es conocido como un vector.

Un array de dos dimensiones también es conodico como una matriz.

Un array de tres dimensiones también es conocido como un cubo, etc.

Existen diferentes funciones que permiten agregar arrays, donde se especifica las dimensiones que se quieran tener, como lo son:
np.empty(dimensiones)-Array vacío.

np.zeros(dimensiones)-Array con elementos cero.

np.ones(dimensiones)-Array con elementos uno.

np.full(dimensiones, valor)-Array con todos los elementos un valor.

np.identity(n)-Crea y devuelve una referencia a la matriz identidad de dimensión n.

np.arange(inicio, fin, salto)-Array con elementos que son la secuencia con un inicio y un fintomando valores cada salto.

np.linspace(inicio, fin, n)-Array de una dimensión con elementos que son la secuencia de n valores equidistantes.

np.random.random(dimensiones)-Array con la tupla dimensiones cuyos elementos son aleatorios.

In [5]:
#Ejemplo de array con unos
import numpy as np
m=np.ones(3)
print (m)

[1. 1. 1.]


In [6]:
#Ejemplo de matriz identidad I4
import numpy as np
n=np.identity(4)
print (n)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Para poder acceder a los elementos de un array se utilizan índices (que comienzan en $0$).

También, se puede obtener subarrays con el operador dos puntos : indicando el índice inicial y el siguiente al final para cada dimensión.

In [7]:
import numpy as np
m=np.array([[1, 2, 3], [4, 5, 6]])
print(m[1, 2]) #Elemento que se quiere en fila, colúmna

6


Además, se pueden filtrar los elementos de un array dependiendo de si cumplen la condición que pida

También, se pueden hacer operaciones con arrays, como los son la suma $(+)$, resta $(-)$, división $(/)$ e incluso elevarlos a exponentes $(**)$.

Además, como los arrays de segunda dimensión son considerados matrices, se puede realizar multiplicación escalar $(@)$, la norma de un vector,
la transpuesta de una matriz, su traza, determinante o la matriz inversa.

In [9]:
import numpy as np
m=np.array([1, 2, 3])
n=np.array([4, 5, 6])
o=np.array([[1, 2, 3], [4, 5, 6]])
p=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print (m+n) #Suma
print (m-n) #Resta
print (m**2) #Elevar a un exponente
print (m/n) #División
print (m@n) #Multiplicaión escalar
print(np.linalg.norm(m)) #Módulo
print(m.T) #Transpuesta de la matriz
print (o.trace()) #Traza de la matriz
print(np.linalg.det(p)) #Determinate de la matriz

[5 7 9]
[-3 -3 -3]
[1 4 9]
[0.25 0.4  0.5 ]
32
3.7416573867739413
[1 2 3]
6
0.0


Puede ayudar a resolver sistemas de ecuaciones, donde el array $a$ son los coeficientes de la incógnitas y el array $b$ los valores
independientes.

In [11]:
import numpy as np
#Sistema de ecuación lineal 3x3
#2x+3y-2z=5
#3x-4y+3z=8
#2x-4y-2z=6
a=np.array([[5, -2, 1], [2, 5, -2], [1, -4, 3]])
b = np.array([24, -14, 26])
print(np.linalg.solve(a, b)) #Valores de x, y, z

[ 3. -2.  5.]
